#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-muhaz
Version  : 1.2.6.4
Release  : 45
URL      : https://cran.r-project.org/src/contrib/muhaz_1.2.6.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/muhaz_1.2.6.4.tar.gz
Summary  : Hazard Function Estimation in Survival Analysis
Group    : Development/Tools
License  : GPL-2.0
Requires: R-muhaz-lib = %{version}-%{release}
Requires: R-muhaz-license = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
function for censored data.

%package lib
Summary: lib components for the R-muhaz package.
Group: Libraries
Requires: R-muhaz-license = %{version}-%{release}

%description lib
lib components for the R-muhaz package.


%package license
Summary: license components for the R-muhaz package.
Group: Default

%description license
license components for the R-muhaz package.


%prep
%setup -q -n muhaz
pushd ..
cp -a muhaz buildavx2
popd
pushd ..
cp -a muhaz buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737151502

%install
export SOURCE_DATE_EPOCH=1737151502
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-muhaz
cp %{_builddir}/muhaz/COPYING %{buildroot}/usr/share/package-licenses/R-muhaz/dfac199a7539a404407098a2541b9482279f690d || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/muhaz/DESCRIPTION
/usr/lib64/R/library/muhaz/INDEX
/usr/lib64/R/library/muhaz/Meta/Rd.rds
/usr/lib64/R/library/muhaz/Meta/features.rds
/usr/lib64/R/library/muhaz/Meta/hsearch.rds
/usr/lib64/R/library/muhaz/Meta/links.rds
/usr/lib64/R/library/muhaz/Meta/nsInfo.rds
/usr/lib64/R/library/muhaz/Meta/package.rds
/usr/lib64/R/library/muhaz/NAMESPACE
/usr/lib64/R/library/muhaz/R/muhaz
/usr/lib64/R/library/muhaz/R/muhaz.rdb
/usr/lib64/R/library/muhaz/R/muhaz.rdx
/usr/lib64/R/library/muhaz/help/AnIndex
/usr/lib64/R/library/muhaz/help/aliases.rds
/usr/lib64/R/library/muhaz/help/muhaz.rdb
/usr/lib64/R/library/muhaz/help/muhaz.rdx
/usr/lib64/R/library/muhaz/help/paths.rds
/usr/lib64/R/library/muhaz/html/00Index.html
/usr/lib64/R/library/muhaz/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/muhaz/libs/muhaz.so
/V4/usr/lib64/R/library/muhaz/libs/muhaz.so
/usr/lib64/R/library/muhaz/libs/muhaz.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-muhaz/dfac199a7539a404407098a2541b9482279f690d
